name: so_money
description: A starting point for Dart libraries or applications.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.5

dependencies:
  intl: ^0.18.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
