name: so_money
description: This package provides classes required to manipulate monetary values including arithmetic operations and comparisons.
version: 0.0.7
repository: https://github.com/syampillai/so_money

environment:
  sdk: ^3.5.4

dependencies:
  intl: ^0.19.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.5
