name: so_money
description: This package provides classes required to manipulate monetary values including arithmetic operations and comparisons.
version: 0.0.5
repository: https://github.com/syampillai/so_money

environment:
  sdk: ^3.3.3

dependencies:
  intl: ^0.19.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.3
